### ISSUE TITLE
¿mostrar()?

### ISSUE THREAD

**Issue by rdelcastillo** [kretinoh/ProgramacionDAW#10]
https://github.com/kretinoh/ProgramacionDAW/blob/92eb2b0a55733318558cb237f2b019834b6f326e/Programacion/src/gestisimal/Almacen.java#L108

**Comment by kretinoh** [comment]
Muestro un articulo en específico

**Comment by rdelcastillo** [comment]
No muestras nada, DEVUELVES un artículo convertido a String, es diferente.

**Comment by kretinoh** [comment]
he refactorizado el nombre de mostrar() a devolverArticuloAlmacen()
