### ISSUE TITLE
¿Por qué en mayúsculas?

### ISSUE THREAD

**Issue by rdelcastillo** [kretinoh/ProgramacionDAW#2]
https://github.com/kretinoh/ProgramacionDAW/blob/92eb2b0a55733318558cb237f2b019834b6f326e/Programacion/src/gestisimal/Articulo.java#L15

**Comment by kretinoh** [comment]
En otros ejemplos algunas variables estáticas la poníamos en mayúsculas, por lo que decidí hacer lo mismo

**Comment by rdelcastillo** [comment]
No las poníamos en mayúsculas por ser estáticas, lo hacíamos por ser CONSTANTES. No es el caso.
